#robot_radius: 0.5
footprint: [[-0.21, 0.31], [0.215, 0.31], [0.363, 0], [0.215, -0.31], [-0.21, -0.31]]
footprint_padding: 0.01 #0.075

transform_tolerance: 0.5
map_type: costmap

always_send_full_costmap: false

obstacle_layer:
  enabled: true
  inflation_radius: 0.1
  track_unknown_space: true
  combination_method: 1
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    topic: scan
    sensor_frame: lidar
    data_type: LaserScan
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    inf_is_valid: true


inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"