shutdown_costmaps: false

controller_frequency: 10.0 #10.0
controller_patience: 15.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 0.0 #10.0
oscillation_distance: 0.5

recovery_behavior_enabled: true

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 1.5
  layer_names: ["obstacle_layer"]
aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_layer"]


