obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.21, 0.31], [0.215, 0.31], [0.363, 0], [0.215, -0.31], [-0.21, -0.31]]
footprint_padding: 0.075
#robot_radius: 0.105

inflation_radius: 0.1
cost_scaling_factor: 4.5

map_type: costmap
observation_sources: scan
scan: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}