DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.4
  min_vel_x: 0.3

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.4
  min_vel_trans:  0.28

  max_vel_theta: 1.0
  min_vel_theta: 0.7

  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_lim_theta: 6.0 
  acc_lim_trans: 0.5

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 30.0
  goal_distance_bias: 20.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Global Plan Parameters
  prune_plan: true

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true

  theta_stopped_vel: 0.7
  trans_stopped_vel: 0.25