local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0 #2.0
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05 #0.1
  transform_tolerance: 0.5
  
  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

######################################################

# local_costmap:
#   global_frame: map
#   robot_base_frame: base_link

#   update_frequency: 1.0
#   publish_frequency: 1.0
#   transform_tolerance: 0.5  

#   static_map: false  
#   rolling_window: true
#   width: 3
#   height: 3
#   resolution: 0.05
#   track_unknown_space: false
