axis_linear: 7 # Dpad UP/DOWN
scale_linear: 0.5
scale_linear_turbo: 1.0

axis_angular: 6 # Dpad LEFT/RIGHT
scale_angular: 1.0
scale_angular_turbo: 2.0

enable_button: 0  # A button
enable_turbo_button: 1  # B button